default: &default
  adapter: postgresql
  encoding: unicode
  database: hearthstone_arena_tracker
  pool: 5

development:
  <<: *default
  host: localhost
  username: hat_demo
  password: hat_demo

test:
  <<: *default
  host: localhost
  database: hearthstone_arena_tracker_test
  username: hat_demo_test
  password: hat_demo_test

production:
  <<: *default
